### PR TITLE
Update

### PR DESCRIPTION
**Pull request by trichter**
Since people show interest in this package, I put some effort into it. It is a bit slimmer now, but has to be installed properly. I also added some convenient functions for direct retrieval of timeseries/spectra and for plotting.

### CODE REVIEW

**Comment by wg1562** [comment]
Has anyone who has tried this pull still getting the error described in [https://github.com/hydrogeoscience/pygtide/issues/11](url)

with unrecognized date format in the etpolut1.dat file?

**Comment by trichter** [comment]
I did not encounter that error. You might want to install this branch and try it yourself.

**Comment by Jollyfant** [comment]
Hi @trichter, I couldn't figure out how to get `pygtide` running from the main repo but your branch worked like a charm. Just wanted to let you know and thank you for the work.

**Comment by strawpants** [comment]
Dear @trichter, thanks for this! I'm cc-ing @hydrogeoscience because I think this is a valuable pull request, and should be considered.

**Comment by hydrogeoscience** [comment]
This is now obsolete and we are working on a new version that compiles from Fortran source.

**Pull request closed without merging**
